### PR TITLE
Ruby rails update

### PR DESCRIPTION
**Pull request by techgique**
This is just done by manually changing `.ruby-version` for the first commit, running `cd .` so RVM picks up that you want to use a different version of Ruby, `gem install bundler` so it has Bundler 2+, and then running `bundle update` so Bundler pulls the latest version of all the dependencies. This last step is what pulls in a newer version of Rails which addresses the mimemagic mess.

### CODE REVIEW

**Comment by techgique** [comment]
I checked by running the Rails app locally as well as running `rails test` on the command line to make sure tests still pass :+1:

**Comment by techgique** [comment]
Also now deployed on dev1 for testing: https://cdrhdev1.unl.edu/api/v1/
And upon quick glance apps using that seem to be working

**Comment by techgique** [comment]
Fyi, the RVM documentation reminded me that `rvm @global do gem install bundler` will save us the hassle of having to run `gem install bundler` for each gemset using a Ruby version :man_facepalming:

**Review by wkdewey — COMMENTED** [review]
Do we want to do this on the project repos, too?

**Pull request merged**
